---
title: ANTECEDENTES Página 3
---

###**Dónde trabajar**

Según el tema, podrá destinar gran parte de su tiempo a trabajar en su localidad en contacto con los responsables de políticas públicas, o a escala nacional podrá utilizar su tiempo en la capital, asistiendo a charlas con el fin de entablar lazos y formar coaliciones. Dado que el lugar donde se desarrollan los debates sobre el Internet Libre y Abierto o gobernanza de Internet varían según el país, usted deberá explorar individualmente estos ámbitos como tarea para este módulo.

###**Foros Internacionales y Nacionales, y las Relaciones entre Ellos**

![]({{site.baseurl}}/img/Module 3/Module 3-3.png)
*Imagen: de <a href="http://www.flickr.com/photos/internetsociety/8163605644" target="_blank">Internet Society</a>, proporcionada bajo licencia <a href="https://creativecommons.org/licenses/by-nc-sa/2.0/" target="_blank">CC BY-NC-SA 2.0</a>*

A nivel internacional y nacional, hay varios foros de gobernanza de Internet donde se debate y se toman decisiones sobre el Internet Libre y Abierto. Estos foros de gobernanza de Internet pueden clasificarse en múltiples categorías, incluidos procesos de la ONU o de la Cumbre Mundial sobre la Sociedad de la Información (CMSI), foros de la Unión Internacional de Telecomunicaciones (UIT), el Foro de Gobernanza de Internet (FGI) y foros técnicos. Además de estos foros de gobernanza de Internet formales, también se producen decisiones y deliberaciones sobre el tema en debates dentro de gobiernos nacionales, organizaciones regionales como la Unión Europea y la Organización de los Estados Americanos, así como a través de acuerdos de comercio, un tema que se analizará en el módulo 10. En este curso, nos enfocaremos principalmente en procesos de foros tradicionales de gobernanza de Internet, debido a la enorme magnitud de estos foros en ese ámbito.

Cada serie de los foros mencionados anteriormente tienen criterios propios en cuanto a cuáles actores interesados pueden participar, y algunos optan por trabajar tanto dentro de estos foros como en forma externa a ellos. La UIT y numerosos procesos de la ONU solo se desarrollan a nivel internacional y reconocen a los gobiernos el mayor nivel de preponderancia en cuanto a decisiones y participación. Esta sección abordará los foros y procesos en los cuales usted puede participar en forma individual o como parte de una organización.

El FGI es un foro internacional anual creado por la ONU que reúne a múltiples partes interesadas, y posibilita el debate de políticas entre distintos actores sobre temas relativos a la gobernanza de Internet. Si bien el FGI no tiene poder de decisión, varios organismos y partes interesadas han sostenido que debería tener mayores potestades. En un plano más regional, también hay capítulos regionales y nacionales del FGI, incluido el FGI de América Latina y el Caribe (LACIGF), LACIGF y otros FGI más pequeños son en general libres y abiertos al público y a todo tipo de interesados, y contribuyen a definir las prioridades de un país/región para el FGI global. En general, los participantes y las partes interesadas pueden sugerir temas en el programa y los paneles, por lo que su FGI local sería una plataforma propicia para generar conciencia sobre su causa y reunir apoyo para su tema a nivel nacional, regional y posiblemente internacional. 

Si le interesan las funciones técnicas de Internet, la Corporación para la Asignación de Nombres y Números en Internet (Internet Corporation for Names and Numbers, ICANN) mantiene encuentros internacionales de público acceso tres veces al año en distintos países y continentes. Tales reuniones permiten que las partes interesadas debatan y posiblemente participen en los procesos de toma de decisiones vinculados con sistemas de asignación de nombres en Internet. También hay Registros Internacionales de Internet (Regional Internet Registries, RIR), como el Registro de Direcciones de Internet para América Latina y Caribe (Latin American and Caribbean Network Information Centre, LACNIC), que celebran encuentros públicos y seminarios.

Otro ámbito importante para debates sobre gobernanza de Internet es la Internet Society (ISOC). Internet Society, de alcance global, no es un organismo formal donde se adopten decisiones sobre gobernanza de Internet, sino un espacio donde aquellos interesados en difundir la importancia de Internet para el bienestar de la sociedad podrán encontrar convicciones compartidas. ISOC cuenta con numerosos capítulos nacionales, entre ellos ISOC Ecuador e ISOC Perú, que organizan eventos, debates y análisis sobre gobernanza de Internet, derechos humanos e Internet, y acceso a Internet. Los capítulos trabajan además en proyectos de desarrollo y políticas públicas vinculados con Internet que contribuyen a la meta global de ISOC.

Si usted trabaja para promover cambios a nivel global, evalúe como podría obtener fondos para asistir a encuentros y foros internacionales al elaborar su diagrama GROW u otro plan estratégico. Asimismo, si es de su interés y conveniencia, podrá averiguar si usted y sus socios en la coalición pueden unirse a delegaciones oficiales de sus gobiernos que vayan a participar en estos eventos.
